server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html home.html;

    # Shared portal pages
    location = / {
        try_files /index.html =404;
    }

    location = /home.html {
        try_files /home.html =404;
    }

    location = /login.html {
        try_files /login.html =404;
    }

    location = /register.html {
        try_files /register.html =404;
    }

    location /css/ {
        try_files $uri =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location = /auth.js {
        try_files /auth.js =404;
    }


    #Frontends
    location /enrolment/ {
        proxy_pass http://enrolment-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /assessments/ {
        proxy_pass http://priority-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /calendar/ {
        proxy_pass http://calendar-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /notes/ {
        proxy_pass http://notebook-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /exams/ {
        proxy_pass http://exam-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # Shared authentication API
    location /auth-api/ {
        proxy_pass http://auth-backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # Feature APIs
    location /enrolment-api/ {
        proxy_pass http://enrolment-backend:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /assessments-api/ {
        proxy_pass http://priority-backend:5007/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /calendar-api/ {
        proxy_pass http://calendar-backend:5005/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /notes-api/ {
        proxy_pass http://notebook-backend:5003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /exams-api/ {
        proxy_pass http://exam-backend:5009/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}