services:
    exam-frontend:
        build:
            context: ./frontend
        container_name: frontend-cayden
        ports:
            - "8080:80"
        depends_on:
            - exam-backend
        networks:
            - enrolment-network
        restart: unless-stopped

    exam-backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: backend-cayden
        ports:
            - "5001:5001"
        environment:
            DATABASE_SERVICE_URL: http://exam-database:5002
            OLLAMA_BASE_URL: http://host.docker.internal:11434/v1
            OLLAMA_MODEL: qwen2.5:0.5b
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - exam-database
        networks:
            - enrolment-network
        restart: unless-stopped

    exam-database:
        build:
            context: ./database
        container_name: exam-database
        ports:
            - "5002:5002"
        volumes:
            - database_data:/app/data
        networks:
            enrolment-network:
                aliases:
                    - exam-database 
        restart: unless-stopped

volumes:
    database_data:

networks:
    enrolment-network:
        driver: bridge