name: Yunchung Chang CI

on:
    push:
        paths:
            - "student-yunchungchang/**"
            - ".github/workflows/student-yunchungchang-ci.yml"

    pull_request:
        paths:
            - "student-yunchungchang/**"
            - ".github/workflows/student-yunchungchang-ci.yml"

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Docker services
              run: docker compose -f student-yunchungchang/docker-compose.fragment.yml build
