name: Yulin Zhu CI

on:
    push:
        paths:
            - "student-yulinzhu/**"
            - "docker-compose.yml"
            - ".github/workflows/student-yulinzhu.yml"
    
    pull_request:
        paths:
            - "student-yulinzhu/**"
            - "docker-compose.yml"
            - ".github/workflows/student-yulinzhu.yml"

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Bulid Docker services
              run: docker compose -f docker-compose.yml build\
                enrolment-database \ enrolment-backend \ enrolment-frontend
